resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:267355803c3a6d32cb354477baddfa9db3f10ab1fca08ad23191d8ef6c0c3152
  name: controller
  newName: ghcr.io/pl4nty/cloudflare-kubernetes-gateway
